color: null
fieldLayouts:
  eea9850b-a3c7-45e0-806d-5c025b290a38:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-06-14T07:36:34+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 8da049ce-3043-402f-bc06-abcf1eaeb43d
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-06-14T07:41:46+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 391fd68c-ad7d-42d8-b9f4-daefbef5a206 # Informations
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 32db97bf-76ab-488f-aa24-85b59a927d4e
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-06-14T07:41:46+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 8a7b9a9a-d534-49e0-aeae-51896bc9dcfb # E-mail
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3682b43c-eabe-4fcd-b8c0-c4e0fb33d84d
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-06-14T07:41:46+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: e4774a18-f4d4-474d-b117-81b2c72a2f0a # Telephone Number
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8d30eb94-473c-420d-936f-3d6f4e21de5b
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-06-14T07:41:46+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 0236b792-3d9d-4357-bfb5-27f0563387ba # Image
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0fbd8f91-7f8c-47ef-a1f3-aa51c73a9d05
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: f1446f76-7f10-45ac-8340-23d3c7a13947
        userCondition: null
handle: about
hasTitleField: true
icon: circle-info
name: about
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
