color: null
fieldLayouts:
  674a9917-6b36-4aef-8eff-61a05c5c6d55:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-05-16T13:17:19+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: b3fb72f0-ce4b-4da2-8925-3f21130763b9
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-05-16T13:19:52+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 0236b792-3d9d-4357-bfb5-27f0563387ba # Image
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c45dca53-2054-4d71-a74d-b568c9176430
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-05-16T13:19:52+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 0236b792-3d9d-4357-bfb5-27f0563387ba # Image
            handle: image2
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f3c31b1d-d728-470d-8b4a-262088e4fc4e
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-05-16T13:19:52+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: bc050c68-33ca-41b4-ba7f-cd9d257a2a8d # About
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c063a88c-285f-4059-bf68-98170682b9bf
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 60e9c77f-d536-4682-8fc2-d01fcc4bea01
        userCondition: null
handle: homepage
hasTitleField: true
icon: house
name: homepage
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
