columnSuffix: null
handle: organisationSelector
instructions: null
name: 'Organisation Selector'
searchable: false
settings:
  customOptions: false
  options:
    -
      __assoc__:
        -
          - label
          - 'Site Mariahuis'
        -
          - value
          - siteMariahuis
        -
          - icon
          - ''
        -
          - color
          - ''
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - Sint-Coleta
        -
          - value
          - sintColeta
        -
          - icon
          - ''
        -
          - color
          - ''
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Checkboxes
