dateModified: 1749818636
email:
  fromEmail: cthijsdewaegeneer@hotmail.com
  fromName: Mariahuis
  transportType: craft\mail\transportadapters\Sendmail
fs:
  assets:
    hasUrls: true
    name: assets
    settings:
      path: assets
    type: craft\fs\Local
    url: /assets/
meta:
  __names__:
    0db241d4-2e06-4fff-a2af-dbf0ea38ed73: 'Public Schema' # Public Schema
    1d5d1177-a90c-47eb-be17-96aa47c1a279: Navigation # Navigation
    02d0d6a6-528f-43d9-9f98-32bc31ce7eff: Footer # Footer
    2db437de-5149-40d3-9abb-2258651c93ec: logo # logo
    2e553777-6e9b-4391-acff-be623de1b9c1: Images # Images
    4a0cf904-6f9d-4504-a707-2ee5b5a08054: home # home
    4a263512-20cf-4cbe-9dda-a9705a47e161: 'Navigation Link URL' # Navigation Link URL
    4b9a158b-4240-4eae-bd16-bd85c81c5374: logo # logo
    8a7b9a9a-d534-49e0-aeae-51896bc9dcfb: E-mail # E-mail
    8fbfce11-5db6-4ffb-92ca-806fed38ec04: Service # Service
    9ed401c1-9929-4eb1-b53d-ef9ec18b7d21: subtiltel # subtiltel
    23d2c635-d212-4d53-8b14-8f0a46f25abb: homepage # homepage
    41f8402d-f330-488f-a911-a74233e603d2: Footer # Footer
    50da2409-03a2-4404-923d-b6e27f251175: Team # Team
    52c56731-5bd7-4925-bc00-8f6bc0cbf175: Images # Images
    57a34491-7665-41a5-a922-ed817af24c0a: Class # Class
    0236b792-3d9d-4357-bfb5-27f0563387ba: Image # Image
    264a95fa-2749-4b66-9b94-d40c2bd1d56b: woonpage # woonpage
    286af14c-e5cc-4afc-81b7-0e63e186e926: 'Sint Coleta' # Sint Coleta
    370c7e06-ba86-44f6-9ebf-818f3cb54765: 'Navigation Logo' # Navigation Logo
    649c743c-cbd3-4cf6-96d7-e0dc5e77b2bf: woon # woon
    949a148f-d172-45ff-bcfc-160d3292a8db: Mariahuis # Mariahuis
    a217ec0c-932b-4abe-8ca1-e7d91d1933bc: 'Organisation Selector' # Organisation Selector
    ad5423b7-11e2-4317-920c-4edbae9759dc: Urllink # Urllink
    b8db649c-bb5e-4502-b98a-849dca1d55f1: URLhome # URLhome
    bc050c68-33ca-41b4-ba7f-cd9d257a2a8d: About # About
    c014c31c-08dc-47f7-b5d4-3b3e539550d9: 'Service Card' # Service Card
    cbe9e6f0-0c8d-485f-b0d9-499af8215148: Mariahuis # Mariahuis
    cff0b4bc-9a95-472d-8a35-34908974fbab: 'Cultuur Colette' # Cultuur Colette
    d95cb219-295a-4149-bc48-ab2daa958bed: Simple # Simple
    db31f351-ad0d-4d61-8349-de63860eb42b: 'Team Card' # Team Card
    dda661cb-3856-4b1b-b3ed-ad85be204bdb: 'Navigation Link URL' # Navigation Link URL
    e53f3f97-c9d8-4279-9c27-9acd49e07a16: Information # Information
    e4774a18-f4d4-474d-b117-81b2c72a2f0a: 'Telephone Number' # Telephone Number
    ebe4e538-9047-4604-9246-2cfde30d1da8: 'Job Title' # Job Title
    fc947245-56f3-40e9-bbd0-f927a5caa500: logo # logo
plugins:
  ckeditor:
    edition: standard
    enabled: true
    schemaVersion: 3.0.0.0
system:
  edition: solo
  live: true
  name: Mariahuis
  schemaVersion: 5.7.0.3
  timeZone: America/Los_Angeles
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  require2fa: false
  requireEmailVerification: true
