defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 23d2c635-d212-4d53-8b14-8f0a46f25abb # homepage
handle: home
maxAuthors: 1
name: home
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  286af14c-e5cc-4afc-81b7-0e63e186e926: # Sint Coleta
    enabledByDefault: true
    hasUrls: true
    template: home/_entry.twig
    uriFormat: home
  cbe9e6f0-0c8d-485f-b0d9-499af8215148: # Mariahuis
    enabledByDefault: true
    hasUrls: true
    template: home/_entry.twig
    uriFormat: home
  cff0b4bc-9a95-472d-8a35-34908974fbab: # Cultuur Colette
    enabledByDefault: true
    hasUrls: true
    template: home/_entry.twig
    uriFormat: home
type: single
