defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: c014c31c-08dc-47f7-b5d4-3b3e539550d9 # Service Card
handle: service
maxAuthors: 1
name: Service
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  28873fc0-5092-43dc-94ff-c29ce0463c2c: # Sint Coleta
    enabledByDefault: true
    hasUrls: true
    template: service/_entry.twig
    uriFormat: 'service/{slug}'
  cbe9e6f0-0c8d-485f-b0d9-499af8215148: # Mariahuis
    enabledByDefault: true
    hasUrls: true
    template: service/_entry.twig
    uriFormat: 'service/{slug}'
  f2fcfcef-2e85-4ee2-94c7-b1ce5abab2ac: # Cultuur Colette
    enabledByDefault: true
    hasUrls: true
    template: service/_entry.twig
    uriFormat: 'service/{slug}'
type: channel
