defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: db31f351-ad0d-4d61-8349-de63860eb42b # Team Card
handle: team
maxAuthors: 1
name: Team
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  286af14c-e5cc-4afc-81b7-0e63e186e926: # Sint Coleta
    enabledByDefault: true
    hasUrls: true
    template: _components/card.twig
    uriFormat: 'team/{slug}'
  cbe9e6f0-0c8d-485f-b0d9-499af8215148: # Mariahuis
    enabledByDefault: true
    hasUrls: true
    template: _components/card.twig
    uriFormat: 'team/{slug}'
structure:
  maxLevels: null
  uid: 7d877a0e-e5c6-4091-b64b-13d5528f24fa
type: structure
